In [1]:
import pandas as pd

In [55]:
c_familysize = pd.read_csv('DEC_00_SF2_PCT026_with_ann.csv')
c_income = pd.read_csv('DEC_00_SF4_PCT088_with_ann.csv')
c_english = pd.read_csv('DEC_00_SF4_QTP17_with_ann.csv')
c_school = pd.read_csv('DEC_00_SF4_QTP19_with_ann.csv')

In [47]:
census1.shape

(2147, 6)

In [60]:
censusmerge.shape

(2105, 205)

In [65]:
c_school.columns

Index([u'Id', u'Population Group', u'Id.1', u'Id2', u'Geography',
       u'Number; SCHOOL ENROLLMENT AND TYPE OF SCHOOL - Population 3 years and over enrolled in school',
       u'Percent; SCHOOL ENROLLMENT AND TYPE OF SCHOOL - Population 3 years and over enrolled in school',
       u'Percent of age group enrolled in school; SCHOOL ENROLLMENT AND TYPE OF SCHOOL - Population 3 years and over enrolled in school',
       u'Number; SCHOOL ENROLLMENT AND TYPE OF SCHOOL - Population 3 years and over enrolled in school - Nursery school, preschool',
       u'Percent; SCHOOL ENROLLMENT AND TYPE OF SCHOOL - Population 3 years and over enrolled in school - Nursery school, preschool',
       ...
       u'Percent of age group enrolled in school; SCHOOL ENROLLMENT, EDUCATIONAL ATTAINMENT, AND EMPLOYMENT STATUS - Population 16 to 19 years - Not enrolled in school - Not high school graduate',
       u'Number; SCHOOL ENROLLMENT, EDUCATIONAL ATTAINMENT, AND EMPLOYMENT STATUS - Population 16 to 19 years - Not enrolled in school - Not high school graduate - Employed civilian',
       u'Percent; SCHOOL ENROLLMENT, EDUCATIONAL ATTAINMENT, AND EMPLOYMENT STATUS - Population 16 to 19 years - Not enrolled in school - Not high school graduate - Employed civilian',
       u'Percent of age group enrolled in school; SCHOOL ENROLLMENT, EDUCATIONAL ATTAINMENT, AND EMPLOYMENT STATUS - Population 16 to 19 years - Not enrolled in school - Not high school graduate - Employed civilian',
       u'Number; SCHOOL ENROLLMENT, EDUCATIONAL ATTAINMENT, AND EMPLOYMENT STATUS - Population 16 to 19 years - Not enrolled in school - Not high school graduate - Unemployed',
       u'Percent; SCHOOL ENROLLMENT, EDUCATIONAL ATTAINMENT, AND EMPLOYMENT STATUS - Population 16 to 19 years - Not enrolled in school - Not high school graduate - Unemployed',
       u'Percent of age group enrolled in school; SCHOOL ENROLLMENT, EDUCATIONAL ATTAINMENT, AND EMPLOYMENT STATUS - Population 16 to 19 years - Not enrolled in school - Not high school graduate - Unemployed',
       u'Number; SCHOOL ENROLLMENT, EDUCATIONAL ATTAINMENT, AND EMPLOYMENT STATUS - Population 16 to 19 years - Not enrolled in school - Not high school graduate - Not in labor force',
       u'Percent; SCHOOL ENROLLMENT, EDUCATIONAL ATTAINMENT, AND EMPLOYMENT STATUS - Population 16 to 19 years - Not enrolled in school - Not high school graduate - Not in labor force',
       u'Percent of age group enrolled in school; SCHOOL ENROLLMENT, EDUCATIONAL ATTAINMENT, AND EMPLOYMENT STATUS - Population 16 to 19 years - Not enrolled in school - Not high school graduate - Not in labor force'],
      dtype='object', length=125)

In [62]:
c_english.shape

(2105, 81)

In [93]:
#creating the columns to merge later

c_familysize['Average family size']
c_english['precenglish'] = c_english['Number; POPULATION 5 YEARS AND OVER BY LANGUAGE SPOKEN AT HOME AND ABILITY TO SPEAK ENGLISH - Population 5 years and over'] 
c_school['school_enrolment'] = c_school['Number; SCHOOL ENROLLMENT AND TYPE OF SCHOOL - Population 3 years and over enrolled in school - Nursery school, preschool']
c_income['precless50k'] = (c_income['Less than $10,000']+ c_income['$10,000 to $14,999']+c_income['$15,000 to $19,999']+c_income['$20,000 to $24,999']+c_income['$25,000 to $29,999']+c_income['$30,000 to $34,999']+c_income['$35,000 to $39,999']+c_income['$40,000 to $44,999']+c_income['$40,000 to $44,999'])/ c_income['Total:']

In [76]:
c_income.columns

Index([u'Id', u'Population Group', u'Id.1', u'Id2', u'Geography', u'Total:',
       u'Less than $10,000', u'$10,000 to $14,999', u'$15,000 to $19,999',
       u'$20,000 to $24,999', u'$25,000 to $29,999', u'$30,000 to $34,999',
       u'$35,000 to $39,999', u'$40,000 to $44,999', u'$45,000 to $49,999',
       u'$50,000 to $59,999', u'$60,000 to $74,999', u'$75,000 to $99,999',
       u'$100,000 to $124,999', u'$125,000 to $149,999',
       u'$150,000 to $199,999', u'$200,000 or more'],
      dtype='object')

In [81]:
c_income['precless50k'] = (c_income['Less than $10,000']+ c_income['$10,000 to $14,999']+c_income['$15,000 to $19,999']+c_income['$20,000 to $24,999']+c_income['$25,000 to $29,999']+c_income['$30,000 to $34,999']+c_income['$35,000 to $39,999']+c_income['$40,000 to $44,999']+c_income['$40,000 to $44,999'])/ c_income['Total:']

In [98]:
mergecensus1 = pd.DataFrame({'Average family size': c_familysize['Average family size'], 'Id2': c_familysize['Id2']})
mergecensus2 = pd.DataFrame({'precenglish': c_english['precenglish'], 'Id2': c_english['Id2']})
mergecensus3 = pd.DataFrame({'school_enrolment': c_school['school_enrolment'] , 'Id2':  c_school['Id2']})
mergecensus4 = pd.DataFrame({'precless50k': c_income['precless50k'] , 'Id2':  c_income['Id2']})

In [103]:
censusmerge = pd.merge (mergecensus1,mergecensus2,  how='inner', on=['Id2'])
censusmerge2 = pd.merge (censusmerge,mergecensus3,  how='inner', on=['Id2'])
censusmerge3 = pd.merge (censusmerge2,mergecensus4,  how='inner', on=['Id2'])

In [104]:
censusmerge3

,Average family size,Id2,precenglish,school_enrolment,precless50k
0,0.00,3651000005000100,12780,0,NaN
1,3.55,3651000005000200,3282,94,0.569012
2,3.55,3651000005000400,3037,41,0.650430
3,3.53,3651000005001100,546,4,0.674603
4,3.27,3651000005001600,4784,92,0.778443
5,3.74,3651000005001700,900,0,0.883268
6,3.45,3651000005002000,8302,98,0.861692
7,3.49,3651000005002300,4040,28,0.933498
8,3.67,3651000005002500,4701,76,0.913823
9,3.60,3651000005002701,2737,64,0.960566
10,3.74,3651000005002702,4201,169,0.918919
11,3.01,3651000005002800,5348,101,0.744492
12,3.47,3651000005003100,1341,22,0.829918
13,3.72,3651000005003300,2798,41,0.876727
14,3.56,3651000005003500,3157,70,0.853943
15,3.25,3651000005003600,7056,92,0.657390
16,3.29,3651000005003700,445,27,0.875776
17,3.51,3651000005003800,1223,16,0.539267
18,3.68,3651000005003900,5481,139,0.835728
19,3.21,3651000005004001,1317,20,0.744792
20,3.68,3651000005004100,4888,127,0.871823
21,3.57,3651000005004300,4464,25,0.803367
22,3.38,3651000005004400,4283,86,0.896402
23,3.19,3651000005004600,1489,62,0.823625
24,3.47,3651000005004700,4972,117,0.919819
25,3.59,3651000005004800,3154,103,0.915432
26,3.52,3651000005005000,9590,366,0.843483
27,3.33,3651000005005200,1911,52,0.888069
28,3.58,3651000005005302,3852,119,0.888172
29,3.55,3651000005005400,5101,102,0.880158
...,...,...,...,...,...
2075,3.24,3651000085019700,1841,48,0.319767
2076,3.30,3651000085020100,3188,67,0.364393
2077,3.81,3651000085020700,4346,104,0.664626
2078,3.41,3651000085020801,7653,158,0.419320
2079,3.47,3651000085020803,4982,114,0.314600
2080,3.35,3651000085020804,5057,97,0.275419
2081,3.50,3651000085021300,3791,73,0.507181
2082,3.67,3651000085021900,913,0,0.739583
2083,3.74,3651000085022300,2086,38,0.576552
2084,3.30,3651000085022600,5679,48,0.406752
2085,3.64,3651000085023100,2989,73,0.501542
2086,3.62,3651000085023900,2763,105,0.471947
2087,3.40,3651000085024400,7683,218,0.304483
2088,3.26,3651000085024700,2165,56,0.582139
2089,3.35,3651000085024800,3529,64,0.381406
2090,3.20,3651000085025100,5463,120,0.370234
2091,3.15,3651000085027301,3442,35,0.339059
2092,3.53,3651000085027302,3604,31,0.344715
2093,2.91,3651000085027702,5592,86,0.544629
2094,3.36,3651000085027703,8322,137,0.433680
2095,3.36,3651000085027704,3727,67,0.430618
2096,3.15,3651000085027900,1696,26,0.241449
2097,3.42,3651000085029102,2192,44,0.376398
2098,3.20,3651000085029103,7087,188,0.373599
2099,3.37,3651000085029104,6480,110,0.391083
2100,3.35,3651000085030301,4477,132,0.471995
2101,3.58,3651000085030302,5635,123,0.468783
2102,3.64,3651000085031901,2923,88,0.803766
2103,3.46,3651000085031902,3744,103,0.621418
2104,3.37,3651000085032300,992,19,0.457399